//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maderna.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
    
        public virtual Status Status1 { get; set; }
        public virtual ICollection<Products> Products { get; set; }

        public static List<Models.Categories> GetAll()
        {
            Maderna.Models.Model1Container1 db = new Maderna.Models.Model1Container1();
            List<Models.Categories> Categories = new List<Models.Categories>();
            var CategoryList = from c in db.Categories select c;
            foreach (var item in CategoryList)
            {
                Categories.Add(item);
            }
            return Categories;
        }
    }
}
