//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Gallery { get; set; }
        public int MainPicture { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string LastUpdate { get; set; }
        public int Status { get; set; }
    
        public virtual Status Status1 { get; set; }
        public virtual Pictures Picture { get; set; }
        public virtual Status Status2 { get; set; }
        public virtual Galleries Gallery1 { get; set; }
    }
}
