//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galleries
    {
        public Galleries()
        {
            this.Products = new HashSet<Products>();
            this.Pictures = new HashSet<Pictures>();
            this.Clients = new HashSet<Clients>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Pictures> Pictures { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
