//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public Pictures()
        {
            this.Clients = new HashSet<Clients>();
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public int Gallery { get; set; }
        public string Path { get; set; }
        public string DateCreated { get; set; }
        public string LastUpdate { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual Galleries Gallery1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
