//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pictures
    {
        public Pictures()
        {
            this.Galleries = new HashSet<Galleries>();
        }
    
        public int Id { get; set; }
        public int Gallery { get; set; }
        public string Path { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Status { get; set; }
    
        public virtual Products Product { get; set; }
        public virtual Clients Client { get; set; }
        public virtual ICollection<Galleries> Galleries { get; set; }
    }
}
