//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Status1 = new HashSet<Status>();
            this.Users = new HashSet<Users>();
            this.Categories = new HashSet<Categories>();
            this.Galleries = new HashSet<Galleries>();
            this.Pictures = new HashSet<Pictures>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Category { get; set; }
        public int Gallery { get; set; }
        public int MainPicture { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Status> Status1 { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Galleries> Galleries { get; set; }
        public virtual ICollection<Pictures> Pictures { get; set; }
    }
}
