//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Categories = new HashSet<Categories>();
            this.Clients = new HashSet<Clients>();
            this.Clients1 = new HashSet<Clients>();
            this.Products = new HashSet<Products>();
            this.Pictures = new HashSet<Pictures>();
            this.Users = new HashSet<Users>();
            this.Galleries = new HashSet<Galleries>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Clients> Clients1 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Pictures> Pictures { get; set; }
        public virtual ICollection<Users> Users { get; set; }
        public virtual ICollection<Galleries> Galleries { get; set; }
    }
}
