//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maderna.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Products Product { get; set; }
        public virtual Categories Category { get; set; }
        public virtual Galleries Gallery { get; set; }
        public virtual Clients Client { get; set; }
        public virtual Users User { get; set; }
    }
}
